name: Backend Actions

on: [push]

permissions:
  contents: write

jobs:
  deploy:
    name: deploy
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    env:
      SANITY_AUTH_TOKEN: ${{ secrets.SANITY_AUTH_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.13.1
          cache: yarn
          cache-dependency-path: backend/yarn.lock

      - name: Install & Deploy
        run: |
          yarn install
          yarn deploy
        working-directory: backend
